# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  kubedb:
    version: v2
    image: ghcr.io/kubedb/vcluster-plugin-kubedb:v0.0.1
    imagePullPolicy: Always
    rbac:
      role:
        extraRules:
          - apiGroups: ["kubedb.com"]
            resources: ["*"]
            verbs: ["*"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["*"]

# Make sure the cluster role is enabled or otherwise the plugin won't be able to watch custom
# resource definitions.
rbac:
  clusterRole:
    enabled: true
  role:
    enabled: true
    extraRules:
      - apiGroups: ["kubedb.com"]
        resources: ["*"]
        verbs: ["*"]
