apiVersion: v1
kind: Pod
metadata:
  name: agent
spec:
  containers:
  - name: agent
    image: nginx
    env:
    # - name: GCP_MARKETPLACE_ENTITLEMENT_ID
    #   valueFrom:
    #     secretKeyRef:
    #       name: fake-reporting-secret
    #       key: entitlement-id
    - name: GCP_MARKETPLACE_ENCODED_KEY
      valueFrom:
        secretKeyRef:
          name: fake-reporting-secret
          key: reporting-key
    - name: GCP_MARKETPLACE_CONSUMER_ID
      valueFrom:
        secretKeyRef:
          name: fake-reporting-secret
          key: consumer-id
